HEADERS += \
    $$PWD/sunspeccommonmodel.h \
    $$PWD/sunspecaggregatormodel.h \
    $$PWD/sunspecinvertersinglephasemodel.h \
    $$PWD/sunspecinvertersplitphasemodel.h \
    $$PWD/sunspecinverterthreephasemodel.h \
    $$PWD/sunspecinvertersinglephasefloatmodel.h \
    $$PWD/sunspecinvertersplitphasefloatmodel.h \
    $$PWD/sunspecinverterthreephasefloatmodel.h \
    $$PWD/sunspecnameplatemodel.h \
    $$PWD/sunspecsettingsmodel.h \
    $$PWD/sunspecstatusmodel.h \
    $$PWD/sunspeccontrolsmodel.h \
    $$PWD/sunspecstoragemodel.h \
    $$PWD/sunspecenergystoragebasemodeldeprecatedmodel.h \
    $$PWD/sunspecpricingmodel.h \
    $$PWD/sunspecvoltvarmodel.h \
    $$PWD/sunspecfreqwattparammodel.h \
    $$PWD/sunspecreactivecurrentmodel.h \
    $$PWD/sunspeclvrtmodel.h \
    $$PWD/sunspechvrtmodel.h \
    $$PWD/sunspecwattpfmodel.h \
    $$PWD/sunspecvoltwattmodel.h \
    $$PWD/sunspecschedulemodel.h \
    $$PWD/sunspecfreqwattmodel.h \
    $$PWD/sunspeclfrtmodel.h \
    $$PWD/sunspechfrtmodel.h \
    $$PWD/sunspeclvrtcmodel.h \
    $$PWD/sunspechvrtcmodel.h \
    $$PWD/sunspeclvrtxmodel.h \
    $$PWD/sunspechvrtxmodel.h \
    $$PWD/sunspeclfrtcmodel.h \
    $$PWD/sunspechfrtcmodel.h \
    $$PWD/sunspeclfrtxmodel.h \
    $$PWD/sunspechfrtxmodel.h \
    $$PWD/sunspecextsettingsmodel.h \
    $$PWD/sunspecmpptmodel.h \
    $$PWD/sunspecmetersinglephasemodel.h \
    $$PWD/sunspecmetersplitsinglephaseabnmodel.h \
    $$PWD/sunspecmeterthreephasemodel.h \
    $$PWD/sunspecmeterthreephasedeltaconnectmodel.h \
    $$PWD/sunspecmetersinglephasefloatmodel.h \
    $$PWD/sunspecmetersplitsinglephasefloatmodel.h \
    $$PWD/sunspecmeterthreephasewyeconnectmodel.h \
    $$PWD/sunspecdeltaconnectthreephaseabcmetermodel.h \
    $$PWD/sunspecsecureacmeterselectedreadingsmodel.h \
    $$PWD/sunspecirradiancemodel.h \
    $$PWD/sunspeclocationmodel.h \
    $$PWD/sunspecrefpointmodel.h \
    $$PWD/sunspecbasemetmodel.h \
    $$PWD/sunspecminimetmodel.h \
    $$PWD/sunspecstringcombinercurrentmodel.h \
    $$PWD/sunspecstringcombineradvancedmodel.h \
    $$PWD/sunspecsolarmodulemodel.h \
    $$PWD/sunspectrackercontrollermodel.h \
    $$PWD/sunspecbatterymodel.h \
    $$PWD/sunspeclithiumionbankmodel.h \
    $$PWD/sunspeclithiumionstringmodel.h \
    $$PWD/sunspeclithiumionmodulemodel.h \
    $$PWD/sunspecflowbatterymodel.h \
    $$PWD/sunspecflowbatterystringmodel.h \
    $$PWD/sunspecflowbatterymodulemodel.h \
    $$PWD/sunspecflowbatterystackmodel.h \
    $$PWD/sunspecmodelfactory.h

SOURCES += \
    $$PWD/sunspeccommonmodel.cpp \
    $$PWD/sunspecaggregatormodel.cpp \
    $$PWD/sunspecinvertersinglephasemodel.cpp \
    $$PWD/sunspecinvertersplitphasemodel.cpp \
    $$PWD/sunspecinverterthreephasemodel.cpp \
    $$PWD/sunspecinvertersinglephasefloatmodel.cpp \
    $$PWD/sunspecinvertersplitphasefloatmodel.cpp \
    $$PWD/sunspecinverterthreephasefloatmodel.cpp \
    $$PWD/sunspecnameplatemodel.cpp \
    $$PWD/sunspecsettingsmodel.cpp \
    $$PWD/sunspecstatusmodel.cpp \
    $$PWD/sunspeccontrolsmodel.cpp \
    $$PWD/sunspecstoragemodel.cpp \
    $$PWD/sunspecenergystoragebasemodeldeprecatedmodel.cpp \
    $$PWD/sunspecpricingmodel.cpp \
    $$PWD/sunspecvoltvarmodel.cpp \
    $$PWD/sunspecfreqwattparammodel.cpp \
    $$PWD/sunspecreactivecurrentmodel.cpp \
    $$PWD/sunspeclvrtmodel.cpp \
    $$PWD/sunspechvrtmodel.cpp \
    $$PWD/sunspecwattpfmodel.cpp \
    $$PWD/sunspecvoltwattmodel.cpp \
    $$PWD/sunspecschedulemodel.cpp \
    $$PWD/sunspecfreqwattmodel.cpp \
    $$PWD/sunspeclfrtmodel.cpp \
    $$PWD/sunspechfrtmodel.cpp \
    $$PWD/sunspeclvrtcmodel.cpp \
    $$PWD/sunspechvrtcmodel.cpp \
    $$PWD/sunspeclvrtxmodel.cpp \
    $$PWD/sunspechvrtxmodel.cpp \
    $$PWD/sunspeclfrtcmodel.cpp \
    $$PWD/sunspechfrtcmodel.cpp \
    $$PWD/sunspeclfrtxmodel.cpp \
    $$PWD/sunspechfrtxmodel.cpp \
    $$PWD/sunspecextsettingsmodel.cpp \
    $$PWD/sunspecmpptmodel.cpp \
    $$PWD/sunspecmetersinglephasemodel.cpp \
    $$PWD/sunspecmetersplitsinglephaseabnmodel.cpp \
    $$PWD/sunspecmeterthreephasemodel.cpp \
    $$PWD/sunspecmeterthreephasedeltaconnectmodel.cpp \
    $$PWD/sunspecmetersinglephasefloatmodel.cpp \
    $$PWD/sunspecmetersplitsinglephasefloatmodel.cpp \
    $$PWD/sunspecmeterthreephasewyeconnectmodel.cpp \
    $$PWD/sunspecdeltaconnectthreephaseabcmetermodel.cpp \
    $$PWD/sunspecsecureacmeterselectedreadingsmodel.cpp \
    $$PWD/sunspecirradiancemodel.cpp \
    $$PWD/sunspeclocationmodel.cpp \
    $$PWD/sunspecrefpointmodel.cpp \
    $$PWD/sunspecbasemetmodel.cpp \
    $$PWD/sunspecminimetmodel.cpp \
    $$PWD/sunspecstringcombinercurrentmodel.cpp \
    $$PWD/sunspecstringcombineradvancedmodel.cpp \
    $$PWD/sunspecsolarmodulemodel.cpp \
    $$PWD/sunspectrackercontrollermodel.cpp \
    $$PWD/sunspecbatterymodel.cpp \
    $$PWD/sunspeclithiumionbankmodel.cpp \
    $$PWD/sunspeclithiumionstringmodel.cpp \
    $$PWD/sunspeclithiumionmodulemodel.cpp \
    $$PWD/sunspecflowbatterymodel.cpp \
    $$PWD/sunspecflowbatterystringmodel.cpp \
    $$PWD/sunspecflowbatterymodulemodel.cpp \
    $$PWD/sunspecflowbatterystackmodel.cpp \
    $$PWD/sunspecmodelfactory.cpp
