/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
* Copyright 2013 - 2022, nymea GmbH
* Contact: contact@nymea.io
*
* This fileDescriptor is part of nymea.
* This project including source code and documentation is protected by
* copyright law, and remains the property of nymea GmbH. All rights, including
* reproduction, publication, editing and translation, are reserved. The use of
* this project is subject to the terms of a license agreement to be concluded
* with nymea GmbH in accordance with the terms of use of nymea GmbH, available
* under https://nymea.io/license
*
* GNU Lesser General Public License Usage
* Alternatively, this project may be redistributed and/or modified under the
* terms of the GNU Lesser General Public License as published by the Free
* Software Foundation; version 3. This project is distributed in the hope that
* it will be useful, but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public License
* along with this project. If not, see <https://www.gnu.org/licenses/>.
*
* For any further details and any questions please contact us under
* contact@nymea.io or see our FAQ/Licensing Information on
* https://nymea.io/license/faq
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
* WARNING
*
* This file has been autogenerated. Any changes in this file may be overwritten.
* If you want to change something, update the register json or the tool.
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef SCHNEIDERIEMMODBUSRTUCONNECTION_H
#define SCHNEIDERIEMMODBUSRTUCONNECTION_H

#include <QObject>

#include <modbusdatautils.h>
#include <hardware/modbus/modbusrtumaster.h>

class SchneiderIEMModbusRtuConnection : public QObject
{
    Q_OBJECT
public:
    enum Registers {
        RegisterCurrentPhaseA = 2999,
        RegisterCurrentPhaseB = 3001,
        RegisterCurrentPhaseC = 3003,
        RegisterVoltagePhaseA = 3027,
        RegisterVoltagePhaseB = 3029,
        RegisterVoltagePhaseC = 3031,
        RegisterPowerPhaseA = 3053,
        RegisterPowerPhaseB = 3055,
        RegisterPowerPhaseC = 3057,
        RegisterTotalCurrentPower = 3059,
        RegisterFrequency = 3109,
        RegisterTotalEnergyConsumed = 3203,
        RegisterTotalEnergyProduced = 3207,
        RegisterEnergyConsumedPhaseA = 3517,
        RegisterEnergyConsumedPhaseB = 3521,
        RegisterEnergyConsumedPhaseC = 3525
    };
    Q_ENUM(Registers)

    explicit SchneiderIEMModbusRtuConnection(ModbusRtuMaster *modbusRtuMaster, quint16 slaveId, QObject *parent = nullptr);
    ~SchneiderIEMModbusRtuConnection() = default;

    ModbusRtuMaster *modbusRtuMaster() const;
    quint16 slaveId() const;

    bool reachable() const;

    uint checkReachableRetries() const;
    void setCheckReachableRetries(uint checkReachableRetries);

    ModbusDataUtils::ByteOrder endianness() const;
    void setEndianness(ModbusDataUtils::ByteOrder endianness);

    /* Total system power [kW] - Address: 3059, Size: 2 */
    float totalCurrentPower() const;

    /* Voltage phase L1 [V] - Address: 3027, Size: 2 */
    float voltagePhaseA() const;

    /* Voltage phase L2 [V] - Address: 3029, Size: 2 */
    float voltagePhaseB() const;

    /* Voltage phase L3 [V] - Address: 3031, Size: 2 */
    float voltagePhaseC() const;

    /* Current phase L1 [A] - Address: 2999, Size: 2 */
    float currentPhaseA() const;

    /* Current phase L2 [A] - Address: 3001, Size: 2 */
    float currentPhaseB() const;

    /* Current phase L3 [A] - Address: 3003, Size: 2 */
    float currentPhaseC() const;

    /* Power phase L1 [kW] - Address: 3053, Size: 2 */
    float powerPhaseA() const;

    /* Power phase L2 [kW] - Address: 3055, Size: 2 */
    float powerPhaseB() const;

    /* Power phase L3 [kW] - Address: 3057, Size: 2 */
    float powerPhaseC() const;

    /* Frequency [Hz] - Address: 3109, Size: 2 */
    float frequency() const;

    /* Total energy consumed [Wh] - Address: 3203, Size: 4 */
    qint64 totalEnergyConsumed() const;

    /* Total energy produced [Wh] - Address: 3207, Size: 4 */
    qint64 totalEnergyProduced() const;

    /* Energy consumed phase A [Wh] - Address: 3517, Size: 4 */
    qint64 energyConsumedPhaseA() const;

    /* Energy consumed phase B [Wh] - Address: 3521, Size: 4 */
    qint64 energyConsumedPhaseB() const;

    /* Energy consumed phase C [Wh] - Address: 3525, Size: 4 */
    qint64 energyConsumedPhaseC() const;

    void updateTotalCurrentPower();
    void updateVoltagePhaseA();
    void updateVoltagePhaseB();
    void updateVoltagePhaseC();
    void updateCurrentPhaseA();
    void updateCurrentPhaseB();
    void updateCurrentPhaseC();
    void updatePowerPhaseA();
    void updatePowerPhaseB();
    void updatePowerPhaseC();
    void updateFrequency();
    void updateTotalEnergyConsumed();
    void updateTotalEnergyProduced();
    void updateEnergyConsumedPhaseA();
    void updateEnergyConsumedPhaseB();
    void updateEnergyConsumedPhaseC();


    ModbusRtuReply *readTotalCurrentPower();
    ModbusRtuReply *readVoltagePhaseA();
    ModbusRtuReply *readVoltagePhaseB();
    ModbusRtuReply *readVoltagePhaseC();
    ModbusRtuReply *readCurrentPhaseA();
    ModbusRtuReply *readCurrentPhaseB();
    ModbusRtuReply *readCurrentPhaseC();
    ModbusRtuReply *readPowerPhaseA();
    ModbusRtuReply *readPowerPhaseB();
    ModbusRtuReply *readPowerPhaseC();
    ModbusRtuReply *readFrequency();
    ModbusRtuReply *readTotalEnergyConsumed();
    ModbusRtuReply *readTotalEnergyProduced();
    ModbusRtuReply *readEnergyConsumedPhaseA();
    ModbusRtuReply *readEnergyConsumedPhaseB();
    ModbusRtuReply *readEnergyConsumedPhaseC();

    virtual bool initialize();
    virtual bool update();

signals:
    void reachableChanged(bool reachable);
    void checkReachabilityFailed();
    void checkReachableRetriesChanged(uint checkReachableRetries);

    void initializationFinished(bool success);
    void updateFinished();

    void endiannessChanged(ModbusDataUtils::ByteOrder endianness);

    void totalCurrentPowerChanged(float totalCurrentPower);
    void totalCurrentPowerReadFinished(float totalCurrentPower);
    void voltagePhaseAChanged(float voltagePhaseA);
    void voltagePhaseAReadFinished(float voltagePhaseA);
    void voltagePhaseBChanged(float voltagePhaseB);
    void voltagePhaseBReadFinished(float voltagePhaseB);
    void voltagePhaseCChanged(float voltagePhaseC);
    void voltagePhaseCReadFinished(float voltagePhaseC);
    void currentPhaseAChanged(float currentPhaseA);
    void currentPhaseAReadFinished(float currentPhaseA);
    void currentPhaseBChanged(float currentPhaseB);
    void currentPhaseBReadFinished(float currentPhaseB);
    void currentPhaseCChanged(float currentPhaseC);
    void currentPhaseCReadFinished(float currentPhaseC);
    void powerPhaseAChanged(float powerPhaseA);
    void powerPhaseAReadFinished(float powerPhaseA);
    void powerPhaseBChanged(float powerPhaseB);
    void powerPhaseBReadFinished(float powerPhaseB);
    void powerPhaseCChanged(float powerPhaseC);
    void powerPhaseCReadFinished(float powerPhaseC);
    void frequencyChanged(float frequency);
    void frequencyReadFinished(float frequency);
    void totalEnergyConsumedChanged(qint64 totalEnergyConsumed);
    void totalEnergyConsumedReadFinished(qint64 totalEnergyConsumed);
    void totalEnergyProducedChanged(qint64 totalEnergyProduced);
    void totalEnergyProducedReadFinished(qint64 totalEnergyProduced);
    void energyConsumedPhaseAChanged(qint64 energyConsumedPhaseA);
    void energyConsumedPhaseAReadFinished(qint64 energyConsumedPhaseA);
    void energyConsumedPhaseBChanged(qint64 energyConsumedPhaseB);
    void energyConsumedPhaseBReadFinished(qint64 energyConsumedPhaseB);
    void energyConsumedPhaseCChanged(qint64 energyConsumedPhaseC);
    void energyConsumedPhaseCReadFinished(qint64 energyConsumedPhaseC);

protected:
    float m_totalCurrentPower = 0;
    float m_voltagePhaseA = 0;
    float m_voltagePhaseB = 0;
    float m_voltagePhaseC = 0;
    float m_currentPhaseA = 0;
    float m_currentPhaseB = 0;
    float m_currentPhaseC = 0;
    float m_powerPhaseA = 0;
    float m_powerPhaseB = 0;
    float m_powerPhaseC = 0;
    float m_frequency = 0;
    qint64 m_totalEnergyConsumed = 0;
    qint64 m_totalEnergyProduced = 0;
    qint64 m_energyConsumedPhaseA = 0;
    qint64 m_energyConsumedPhaseB = 0;
    qint64 m_energyConsumedPhaseC = 0;

    void processTotalCurrentPowerRegisterValues(const QVector<quint16> values);
    void processVoltagePhaseARegisterValues(const QVector<quint16> values);
    void processVoltagePhaseBRegisterValues(const QVector<quint16> values);
    void processVoltagePhaseCRegisterValues(const QVector<quint16> values);
    void processCurrentPhaseARegisterValues(const QVector<quint16> values);
    void processCurrentPhaseBRegisterValues(const QVector<quint16> values);
    void processCurrentPhaseCRegisterValues(const QVector<quint16> values);
    void processPowerPhaseARegisterValues(const QVector<quint16> values);
    void processPowerPhaseBRegisterValues(const QVector<quint16> values);
    void processPowerPhaseCRegisterValues(const QVector<quint16> values);
    void processFrequencyRegisterValues(const QVector<quint16> values);
    void processTotalEnergyConsumedRegisterValues(const QVector<quint16> values);
    void processTotalEnergyProducedRegisterValues(const QVector<quint16> values);
    void processEnergyConsumedPhaseARegisterValues(const QVector<quint16> values);
    void processEnergyConsumedPhaseBRegisterValues(const QVector<quint16> values);
    void processEnergyConsumedPhaseCRegisterValues(const QVector<quint16> values);


    void handleModbusError(ModbusRtuReply::Error error);
    void testReachability();

private:
    ModbusRtuMaster *m_modbusRtuMaster = nullptr;
    ModbusDataUtils::ByteOrder m_endianness = ModbusDataUtils::ByteOrderBigEndian;
    quint16 m_slaveId = 1;

    bool m_reachable = false;
    ModbusRtuReply *m_checkRechableReply = nullptr;
    uint m_checkReachableRetries = 0;
    uint m_checkReachableRetriesCount = 0;
    bool m_communicationWorking = false;
    quint8 m_communicationFailedMax = 15;
    quint8 m_communicationFailedCounter = 0;

    QVector<ModbusRtuReply *> m_pendingInitReplies;
    QVector<ModbusRtuReply *> m_pendingUpdateReplies;

    QObject *m_initObject = nullptr;
    void verifyInitFinished();
    void finishInitialization(bool success);

    void verifyUpdateFinished();

    void onReachabilityCheckFailed();
    void evaluateReachableState();

};

QDebug operator<<(QDebug debug, SchneiderIEMModbusRtuConnection *schneiderIEMModbusRtuConnection);

#endif // SCHNEIDERIEMMODBUSRTUCONNECTION_H
